# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_bulk(self) -> None:
        """Test case for get_v1_bulk

        /v1/bulk/{job_id}
        """
        pass

    def test_get_v1_bulk_results(self) -> None:
        """Test case for get_v1_bulk_results

        Retrieve bulk verification results
        """
        pass

    def test_post_v0_check_email(self) -> None:
        """Test case for post_v0_check_email

        /v0/check_email
        """
        pass

    def test_post_v1_bulk(self) -> None:
        """Test case for post_v1_bulk

        /v1/bulk
        """
        pass

    def test_post_v1_check_email(self) -> None:
        """Test case for post_v1_check_email

        /v1/check_email
        """
        pass


if __name__ == '__main__':
    unittest.main()
