# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.check_email_output_mx import CheckEmailOutputMx

class TestCheckEmailOutputMx(unittest.TestCase):
    """CheckEmailOutputMx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckEmailOutputMx:
        """Test CheckEmailOutputMx
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckEmailOutputMx`
        """
        model = CheckEmailOutputMx()
        if include_optional:
            return CheckEmailOutputMx(
                accepts_mail = True,
                records = [
                    ''
                    ],
                type = '',
                message = ''
            )
        else:
            return CheckEmailOutputMx(
                accepts_mail = True,
                records = [
                    ''
                    ],
                type = '',
                message = '',
        )
        """

    def testCheckEmailOutputMx(self):
        """Test CheckEmailOutputMx"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
