# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.yahoo_verif_method import YahooVerifMethod

class TestYahooVerifMethod(unittest.TestCase):
    """YahooVerifMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYahooVerifMethod(self):
        """Test YahooVerifMethod"""
        # inst = YahooVerifMethod()

if __name__ == '__main__':
    unittest.main()
