# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.hotmail_b2_b_verif_method import HotmailB2BVerifMethod

class TestHotmailB2BVerifMethod(unittest.TestCase):
    """HotmailB2BVerifMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHotmailB2BVerifMethod(self):
        """Test HotmailB2BVerifMethod"""
        # inst = HotmailB2BVerifMethod()

if __name__ == '__main__':
    unittest.main()
