# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.get_v1_bulk200_response import GetV1Bulk200Response

class TestGetV1Bulk200Response(unittest.TestCase):
    """GetV1Bulk200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetV1Bulk200Response:
        """Test GetV1Bulk200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetV1Bulk200Response`
        """
        model = GetV1Bulk200Response()
        if include_optional:
            return GetV1Bulk200Response(
                job_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_records = 56,
                total_processed = 56,
                summary = playbookmedia_email-verification_sdk.models.get_v1_bulk_200_response_summary.get_v1_bulk_200_response_summary(
                    total_safe = 56, 
                    total_invalid = 56, 
                    total_risky = 56, 
                    total_unknown = 56, ),
                job_status = 'Running'
            )
        else:
            return GetV1Bulk200Response(
                job_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_records = 56,
                total_processed = 56,
                summary = playbookmedia_email-verification_sdk.models.get_v1_bulk_200_response_summary.get_v1_bulk_200_response_summary(
                    total_safe = 56, 
                    total_invalid = 56, 
                    total_risky = 56, 
                    total_unknown = 56, ),
                job_status = 'Running',
        )
        """

    def testGetV1Bulk200Response(self):
        """Test GetV1Bulk200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
