# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.smtp_details import SmtpDetails

class TestSmtpDetails(unittest.TestCase):
    """SmtpDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmtpDetails:
        """Test SmtpDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmtpDetails`
        """
        model = SmtpDetails()
        if include_optional:
            return SmtpDetails(
                can_connect_smtp = True,
                has_full_inbox = True,
                is_catch_all = True,
                is_deliverable = True,
                is_disabled = True
            )
        else:
            return SmtpDetails(
                can_connect_smtp = True,
                has_full_inbox = True,
                is_catch_all = True,
                is_deliverable = True,
                is_disabled = True,
        )
        """

    def testSmtpDetails(self):
        """Test SmtpDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
