# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.check_email_request import CheckEmailRequest

class TestCheckEmailRequest(unittest.TestCase):
    """CheckEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckEmailRequest:
        """Test CheckEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckEmailRequest`
        """
        model = CheckEmailRequest()
        if include_optional:
            return CheckEmailRequest(
                from_email = '',
                to_email = '',
                hello_name = '',
                proxy = playbookmedia_email-verification_sdk.models.check_email_input_proxy.CheckEmailInputProxy(
                    host = '', 
                    port = 56, 
                    username = '', 
                    password = '', ),
                smtp_port = 1.337,
                gmail_verif_method = 'Api',
                hotmailb2b_verif_method = 'Smtp',
                hotmailb2c_verif_method = 'Smtp',
                yahoo_verif_method = 'Api',
                check_gravatar = True
            )
        else:
            return CheckEmailRequest(
                to_email = '',
        )
        """

    def testCheckEmailRequest(self):
        """Test CheckEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
