# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.misc_details import MiscDetails

class TestMiscDetails(unittest.TestCase):
    """MiscDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MiscDetails:
        """Test MiscDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MiscDetails`
        """
        model = MiscDetails()
        if include_optional:
            return MiscDetails(
                is_disposable = True,
                is_role_account = True,
                gravatar_url = '',
                is_b2c = True
            )
        else:
            return MiscDetails(
                is_disposable = True,
                is_role_account = True,
                is_b2c = True,
        )
        """

    def testMiscDetails(self):
        """Test MiscDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
