# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.get_v1_bulk200_response_summary import GetV1Bulk200ResponseSummary

class TestGetV1Bulk200ResponseSummary(unittest.TestCase):
    """GetV1Bulk200ResponseSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetV1Bulk200ResponseSummary:
        """Test GetV1Bulk200ResponseSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetV1Bulk200ResponseSummary`
        """
        model = GetV1Bulk200ResponseSummary()
        if include_optional:
            return GetV1Bulk200ResponseSummary(
                total_safe = 56,
                total_invalid = 56,
                total_risky = 56,
                total_unknown = 56
            )
        else:
            return GetV1Bulk200ResponseSummary(
                total_safe = 56,
                total_invalid = 56,
                total_risky = 56,
                total_unknown = 56,
        )
        """

    def testGetV1Bulk200ResponseSummary(self):
        """Test GetV1Bulk200ResponseSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
