# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.post_v1_bulk_request import PostV1BulkRequest

class TestPostV1BulkRequest(unittest.TestCase):
    """PostV1BulkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1BulkRequest:
        """Test PostV1BulkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1BulkRequest`
        """
        model = PostV1BulkRequest()
        if include_optional:
            return PostV1BulkRequest(
                input = [
                    ''
                    ],
                webhook = playbookmedia_email-verification_sdk.models.task_webhook.TaskWebhook(
                    on_each_email = playbookmedia_email-verification_sdk.models.webhook.Webhook(
                        url = '', 
                        extra = playbookmedia_email-verification_sdk.models.extra.extra(), ), )
            )
        else:
            return PostV1BulkRequest(
                input = [
                    ''
                    ],
        )
        """

    def testPostV1BulkRequest(self):
        """Test PostV1BulkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
