# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_email-verification_sdk.models.gmail_verif_method import GmailVerifMethod

class TestGmailVerifMethod(unittest.TestCase):
    """GmailVerifMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGmailVerifMethod(self):
        """Test GmailVerifMethod"""
        # inst = GmailVerifMethod()

if __name__ == '__main__':
    unittest.main()
