# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from playbookmedia_email-verification_sdk.models.debug_details_smtp import DebugDetailsSmtp
from playbookmedia_email-verification_sdk.models.duration import Duration
from typing import Optional, Set
from typing_extensions import Self

class DebugDetails(BaseModel):
    """
    DebugDetails
    """ # noqa: E501
    start_time: StrictStr = Field(description="The timestamp when the email verification started.")
    end_time: StrictStr = Field(description="The timestamp when the email verification ended.")
    duration: Duration
    server_name: StrictStr = Field(description="The name of the server that performed the verification.")
    smtp: DebugDetailsSmtp
    __properties: ClassVar[List[str]] = ["start_time", "end_time", "duration", "server_name", "smtp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebugDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of duration
        if self.duration:
            _dict['duration'] = self.duration.to_dict()
        # override the default output from pydantic by calling `to_dict()` of smtp
        if self.smtp:
            _dict['smtp'] = self.smtp.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebugDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "duration": Duration.from_dict(obj["duration"]) if obj.get("duration") is not None else None,
            "server_name": obj.get("server_name"),
            "smtp": DebugDetailsSmtp.from_dict(obj["smtp"]) if obj.get("smtp") is not None else None
        })
        return _obj


