# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GmailVerifMethod(str, Enum):
    """
    Enumeration describing the method used to verify Gmail emails.
    """

    """
    allowed enum values
    """
    API = 'Api'
    SMTP = 'Smtp'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GmailVerifMethod from a JSON string"""
        return cls(json.loads(json_str))


