# coding: utf-8

"""
    Reacher

    ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

    The version of the OpenAPI document: 0.10.0
    Contact: amaury@reacher.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Reachable(str, Enum):
    """
    An enumeration describing the confidence level that the recipient address is valid: `safe`, `risky`, `invalid`, or `unknown`. Refer to our FAQ for detailed definitions: https://help.reacher.email/email-attributes-inside-json.
    """

    """
    allowed enum values
    """
    INVALID = 'invalid'
    UNKNOWN = 'unknown'
    SAFE = 'safe'
    RISKY = 'risky'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Reachable from a JSON string"""
        return cls(json.loads(json_str))


