/*
Reacher

### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

API version: 0.10.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// CheckEmailOutputMisc - Additional information about the email account.
type CheckEmailOutputMisc struct {
	CoreError *CoreError
	MiscDetails *MiscDetails
}

// CoreErrorAsCheckEmailOutputMisc is a convenience function that returns CoreError wrapped in CheckEmailOutputMisc
func CoreErrorAsCheckEmailOutputMisc(v *CoreError) CheckEmailOutputMisc {
	return CheckEmailOutputMisc{
		CoreError: v,
	}
}

// MiscDetailsAsCheckEmailOutputMisc is a convenience function that returns MiscDetails wrapped in CheckEmailOutputMisc
func MiscDetailsAsCheckEmailOutputMisc(v *MiscDetails) CheckEmailOutputMisc {
	return CheckEmailOutputMisc{
		MiscDetails: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CheckEmailOutputMisc) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CoreError
	err = newStrictDecoder(data).Decode(&dst.CoreError)
	if err == nil {
		jsonCoreError, _ := json.Marshal(dst.CoreError)
		if string(jsonCoreError) == "{}" { // empty struct
			dst.CoreError = nil
		} else {
			if err = validator.Validate(dst.CoreError); err != nil {
				dst.CoreError = nil
			} else {
				match++
			}
		}
	} else {
		dst.CoreError = nil
	}

	// try to unmarshal data into MiscDetails
	err = newStrictDecoder(data).Decode(&dst.MiscDetails)
	if err == nil {
		jsonMiscDetails, _ := json.Marshal(dst.MiscDetails)
		if string(jsonMiscDetails) == "{}" { // empty struct
			dst.MiscDetails = nil
		} else {
			if err = validator.Validate(dst.MiscDetails); err != nil {
				dst.MiscDetails = nil
			} else {
				match++
			}
		}
	} else {
		dst.MiscDetails = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CoreError = nil
		dst.MiscDetails = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CheckEmailOutputMisc)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CheckEmailOutputMisc)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CheckEmailOutputMisc) MarshalJSON() ([]byte, error) {
	if src.CoreError != nil {
		return json.Marshal(&src.CoreError)
	}

	if src.MiscDetails != nil {
		return json.Marshal(&src.MiscDetails)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CheckEmailOutputMisc) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CoreError != nil {
		return obj.CoreError
	}

	if obj.MiscDetails != nil {
		return obj.MiscDetails
	}

	// all schemas are nil
	return nil
}

type NullableCheckEmailOutputMisc struct {
	value *CheckEmailOutputMisc
	isSet bool
}

func (v NullableCheckEmailOutputMisc) Get() *CheckEmailOutputMisc {
	return v.value
}

func (v *NullableCheckEmailOutputMisc) Set(val *CheckEmailOutputMisc) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckEmailOutputMisc) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckEmailOutputMisc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckEmailOutputMisc(val *CheckEmailOutputMisc) *NullableCheckEmailOutputMisc {
	return &NullableCheckEmailOutputMisc{value: val, isSet: true}
}

func (v NullableCheckEmailOutputMisc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckEmailOutputMisc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


