/*
Reacher

### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

API version: 0.10.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreError{}

// CoreError Details of an error encountered during the verification process.
type CoreError struct {
	// The type of error.
	Type string `json:"type"`
	// A human-readable description of the error.
	Message string `json:"message"`
}

type _CoreError CoreError

// NewCoreError instantiates a new CoreError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreError(type_ string, message string) *CoreError {
	this := CoreError{}
	this.Type = type_
	this.Message = message
	return &this
}

// NewCoreErrorWithDefaults instantiates a new CoreError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreErrorWithDefaults() *CoreError {
	this := CoreError{}
	return &this
}

// GetType returns the Type field value
func (o *CoreError) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CoreError) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CoreError) SetType(v string) {
	o.Type = v
}

// GetMessage returns the Message field value
func (o *CoreError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CoreError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CoreError) SetMessage(v string) {
	o.Message = v
}

func (o CoreError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *CoreError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreError := _CoreError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreError)

	if err != nil {
		return err
	}

	*o = CoreError(varCoreError)

	return err
}

type NullableCoreError struct {
	value *CoreError
	isSet bool
}

func (v NullableCoreError) Get() *CoreError {
	return v.value
}

func (v *NullableCoreError) Set(val *CoreError) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreError) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreError(val *CoreError) *NullableCoreError {
	return &NullableCoreError{value: val, isSet: true}
}

func (v NullableCoreError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


