{{- if .Values.server.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "email-verification-service.fullname" . }}-server
  labels:
    {{- include "email-verification-service.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "email-verification-service.selectorLabels" . | nindent 4 }}
    component: server
{{- end }}

{{- if .Values.workers.enabled }}
{{- range $worker, $config := .Values.workers.instances }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.name }}
  labels:
    {{- include "email-verification-service.labels" $ | nindent 4 }}
    component: worker
    worker: {{ $config.name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "email-verification-service.selectorLabels" $ | nindent 4 }}
    component: worker
    worker: {{ $config.name }}
{{- end }}
{{- end }}
{{- end }}
