/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CoreError } from './CoreError';
import {
    instanceOfCoreError,
    CoreErrorFromJSON,
    CoreErrorFromJSONTyped,
    CoreErrorToJSON,
} from './CoreError';
import type { MiscDetails } from './MiscDetails';
import {
    instanceOfMiscDetails,
    MiscDetailsFromJSON,
    MiscDetailsFromJSONTyped,
    MiscDetailsToJSON,
} from './MiscDetails';

/**
 * @type CheckEmailOutputMisc
 * Additional information about the email account.
 * @export
 */
export type CheckEmailOutputMisc = CoreError | MiscDetails;

export function CheckEmailOutputMiscFromJSON(json: any): CheckEmailOutputMisc {
    return CheckEmailOutputMiscFromJSONTyped(json, false);
}

export function CheckEmailOutputMiscFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckEmailOutputMisc {
    if (json == null) {
        return json;
    }
    if (instanceOfCoreError(json)) {
        return CoreErrorFromJSONTyped(json, true);
    }
    if (instanceOfMiscDetails(json)) {
        return MiscDetailsFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CheckEmailOutputMiscToJSON(json: any): any {
    return CheckEmailOutputMiscToJSONTyped(json, false);
}

export function CheckEmailOutputMiscToJSONTyped(value?: CheckEmailOutputMisc | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfCoreError(value)) {
        return CoreErrorToJSON(value as CoreError);
    }
    if (instanceOfMiscDetails(value)) {
        return MiscDetailsToJSON(value as MiscDetails);
    }

    return {};
}

