/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Proxy configuration for email verification.
 * @export
 * @interface CheckEmailInputProxy
 */
export interface CheckEmailInputProxy {
    /**
     * The proxy host address.
     * @type {string}
     * @memberof CheckEmailInputProxy
     */
    host: string;
    /**
     * The proxy port number.
     * @type {number}
     * @memberof CheckEmailInputProxy
     */
    port: number;
    /**
     * Username for proxy authentication.
     * @type {string}
     * @memberof CheckEmailInputProxy
     */
    username?: string;
    /**
     * Password for proxy authentication.
     * @type {string}
     * @memberof CheckEmailInputProxy
     */
    password?: string;
}

/**
 * Check if a given object implements the CheckEmailInputProxy interface.
 */
export function instanceOfCheckEmailInputProxy(value: object): value is CheckEmailInputProxy {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    return true;
}

export function CheckEmailInputProxyFromJSON(json: any): CheckEmailInputProxy {
    return CheckEmailInputProxyFromJSONTyped(json, false);
}

export function CheckEmailInputProxyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckEmailInputProxy {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'port': json['port'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function CheckEmailInputProxyToJSON(json: any): CheckEmailInputProxy {
    return CheckEmailInputProxyToJSONTyped(json, false);
}

export function CheckEmailInputProxyToJSONTyped(value?: CheckEmailInputProxy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'port': value['port'],
        'username': value['username'],
        'password': value['password'],
    };
}

