/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyntaxDetails } from './SyntaxDetails';
import {
    SyntaxDetailsFromJSON,
    SyntaxDetailsFromJSONTyped,
    SyntaxDetailsToJSON,
    SyntaxDetailsToJSONTyped,
} from './SyntaxDetails';
import type { CheckEmailOutputSmtp } from './CheckEmailOutputSmtp';
import {
    CheckEmailOutputSmtpFromJSON,
    CheckEmailOutputSmtpFromJSONTyped,
    CheckEmailOutputSmtpToJSON,
    CheckEmailOutputSmtpToJSONTyped,
} from './CheckEmailOutputSmtp';
import type { DebugDetails } from './DebugDetails';
import {
    DebugDetailsFromJSON,
    DebugDetailsFromJSONTyped,
    DebugDetailsToJSON,
    DebugDetailsToJSONTyped,
} from './DebugDetails';
import type { Reachable } from './Reachable';
import {
    ReachableFromJSON,
    ReachableFromJSONTyped,
    ReachableToJSON,
    ReachableToJSONTyped,
} from './Reachable';
import type { CheckEmailOutputMisc } from './CheckEmailOutputMisc';
import {
    CheckEmailOutputMiscFromJSON,
    CheckEmailOutputMiscFromJSONTyped,
    CheckEmailOutputMiscToJSON,
    CheckEmailOutputMiscToJSONTyped,
} from './CheckEmailOutputMisc';
import type { CheckEmailOutputMx } from './CheckEmailOutputMx';
import {
    CheckEmailOutputMxFromJSON,
    CheckEmailOutputMxFromJSONTyped,
    CheckEmailOutputMxToJSON,
    CheckEmailOutputMxToJSONTyped,
} from './CheckEmailOutputMx';

/**
 * The result of the email verification process.
 * @export
 * @interface CheckEmailOutput
 */
export interface CheckEmailOutput {
    /**
     * The email address that was verified.
     * @type {string}
     * @memberof CheckEmailOutput
     */
    input: string;
    /**
     * 
     * @type {Reachable}
     * @memberof CheckEmailOutput
     */
    is_reachable: Reachable;
    /**
     * 
     * @type {CheckEmailOutputMisc}
     * @memberof CheckEmailOutput
     */
    misc: CheckEmailOutputMisc;
    /**
     * 
     * @type {CheckEmailOutputMx}
     * @memberof CheckEmailOutput
     */
    mx: CheckEmailOutputMx;
    /**
     * 
     * @type {CheckEmailOutputSmtp}
     * @memberof CheckEmailOutput
     */
    smtp: CheckEmailOutputSmtp;
    /**
     * 
     * @type {SyntaxDetails}
     * @memberof CheckEmailOutput
     */
    syntax: SyntaxDetails;
    /**
     * 
     * @type {DebugDetails}
     * @memberof CheckEmailOutput
     */
    debug?: DebugDetails;
}



/**
 * Check if a given object implements the CheckEmailOutput interface.
 */
export function instanceOfCheckEmailOutput(value: object): value is CheckEmailOutput {
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('is_reachable' in value) || value['is_reachable'] === undefined) return false;
    if (!('misc' in value) || value['misc'] === undefined) return false;
    if (!('mx' in value) || value['mx'] === undefined) return false;
    if (!('smtp' in value) || value['smtp'] === undefined) return false;
    if (!('syntax' in value) || value['syntax'] === undefined) return false;
    return true;
}

export function CheckEmailOutputFromJSON(json: any): CheckEmailOutput {
    return CheckEmailOutputFromJSONTyped(json, false);
}

export function CheckEmailOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckEmailOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'],
        'is_reachable': ReachableFromJSON(json['is_reachable']),
        'misc': CheckEmailOutputMiscFromJSON(json['misc']),
        'mx': CheckEmailOutputMxFromJSON(json['mx']),
        'smtp': CheckEmailOutputSmtpFromJSON(json['smtp']),
        'syntax': SyntaxDetailsFromJSON(json['syntax']),
        'debug': json['debug'] == null ? undefined : DebugDetailsFromJSON(json['debug']),
    };
}

export function CheckEmailOutputToJSON(json: any): CheckEmailOutput {
    return CheckEmailOutputToJSONTyped(json, false);
}

export function CheckEmailOutputToJSONTyped(value?: CheckEmailOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'is_reachable': ReachableToJSON(value['is_reachable']),
        'misc': CheckEmailOutputMiscToJSON(value['misc']),
        'mx': CheckEmailOutputMxToJSON(value['mx']),
        'smtp': CheckEmailOutputSmtpToJSON(value['smtp']),
        'syntax': SyntaxDetailsToJSON(value['syntax']),
        'debug': DebugDetailsToJSON(value['debug']),
    };
}

