/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CoreError } from './CoreError';
import {
    instanceOfCoreError,
    CoreErrorFromJSON,
    CoreErrorFromJSONTyped,
    CoreErrorToJSON,
} from './CoreError';
import type { SmtpDetails } from './SmtpDetails';
import {
    instanceOfSmtpDetails,
    SmtpDetailsFromJSON,
    SmtpDetailsFromJSONTyped,
    SmtpDetailsToJSON,
} from './SmtpDetails';

/**
 * @type CheckEmailOutputSmtp
 * Results from connecting to the mail server via SMTP.
 * @export
 */
export type CheckEmailOutputSmtp = CoreError | SmtpDetails;

export function CheckEmailOutputSmtpFromJSON(json: any): CheckEmailOutputSmtp {
    return CheckEmailOutputSmtpFromJSONTyped(json, false);
}

export function CheckEmailOutputSmtpFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckEmailOutputSmtp {
    if (json == null) {
        return json;
    }
    if (instanceOfCoreError(json)) {
        return CoreErrorFromJSONTyped(json, true);
    }
    if (instanceOfSmtpDetails(json)) {
        return SmtpDetailsFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CheckEmailOutputSmtpToJSON(json: any): any {
    return CheckEmailOutputSmtpToJSONTyped(json, false);
}

export function CheckEmailOutputSmtpToJSONTyped(value?: CheckEmailOutputSmtp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfCoreError(value)) {
        return CoreErrorToJSON(value as CoreError);
    }
    if (instanceOfSmtpDetails(value)) {
        return SmtpDetailsToJSON(value as SmtpDetails);
    }

    return {};
}

