/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CoreError } from './CoreError';
import {
    instanceOfCoreError,
    CoreErrorFromJSON,
    CoreErrorFromJSONTyped,
    CoreErrorToJSON,
} from './CoreError';
import type { MxDetails } from './MxDetails';
import {
    instanceOfMxDetails,
    MxDetailsFromJSON,
    MxDetailsFromJSONTyped,
    MxDetailsToJSON,
} from './MxDetails';

/**
 * @type CheckEmailOutputMx
 * Details obtained from querying the mail server's MX records.
 * @export
 */
export type CheckEmailOutputMx = CoreError | MxDetails;

export function CheckEmailOutputMxFromJSON(json: any): CheckEmailOutputMx {
    return CheckEmailOutputMxFromJSONTyped(json, false);
}

export function CheckEmailOutputMxFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckEmailOutputMx {
    if (json == null) {
        return json;
    }
    if (instanceOfCoreError(json)) {
        return CoreErrorFromJSONTyped(json, true);
    }
    if (instanceOfMxDetails(json)) {
        return MxDetailsFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CheckEmailOutputMxToJSON(json: any): any {
    return CheckEmailOutputMxToJSONTyped(json, false);
}

export function CheckEmailOutputMxToJSONTyped(value?: CheckEmailOutputMx | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfCoreError(value)) {
        return CoreErrorToJSON(value as CoreError);
    }
    if (instanceOfMxDetails(value)) {
        return MxDetailsToJSON(value as MxDetails);
    }

    return {};
}

