/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details of an error encountered during the verification process.
 * @export
 * @interface CoreError
 */
export interface CoreError {
    /**
     * The type of error.
     * @type {string}
     * @memberof CoreError
     */
    type: string;
    /**
     * A human-readable description of the error.
     * @type {string}
     * @memberof CoreError
     */
    message: string;
}

/**
 * Check if a given object implements the CoreError interface.
 */
export function instanceOfCoreError(value: object): value is CoreError {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CoreErrorFromJSON(json: any): CoreError {
    return CoreErrorFromJSONTyped(json, false);
}

export function CoreErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreError {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'message': json['message'],
    };
}

export function CoreErrorToJSON(json: any): CoreError {
    return CoreErrorToJSONTyped(json, false);
}

export function CoreErrorToJSONTyped(value?: CoreError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'message': value['message'],
    };
}

