/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DebugDetailsSmtp } from './DebugDetailsSmtp';
import {
    DebugDetailsSmtpFromJSON,
    DebugDetailsSmtpFromJSONTyped,
    DebugDetailsSmtpToJSON,
    DebugDetailsSmtpToJSONTyped,
} from './DebugDetailsSmtp';
import type { Duration } from './Duration';
import {
    DurationFromJSON,
    DurationFromJSONTyped,
    DurationToJSON,
    DurationToJSONTyped,
} from './Duration';

/**
 * 
 * @export
 * @interface DebugDetails
 */
export interface DebugDetails {
    /**
     * The timestamp when the email verification started.
     * @type {string}
     * @memberof DebugDetails
     */
    start_time: string;
    /**
     * The timestamp when the email verification ended.
     * @type {string}
     * @memberof DebugDetails
     */
    end_time: string;
    /**
     * 
     * @type {Duration}
     * @memberof DebugDetails
     */
    duration: Duration;
    /**
     * The name of the server that performed the verification.
     * @type {string}
     * @memberof DebugDetails
     */
    server_name: string;
    /**
     * 
     * @type {DebugDetailsSmtp}
     * @memberof DebugDetails
     */
    smtp: DebugDetailsSmtp;
}

/**
 * Check if a given object implements the DebugDetails interface.
 */
export function instanceOfDebugDetails(value: object): value is DebugDetails {
    if (!('start_time' in value) || value['start_time'] === undefined) return false;
    if (!('end_time' in value) || value['end_time'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('server_name' in value) || value['server_name'] === undefined) return false;
    if (!('smtp' in value) || value['smtp'] === undefined) return false;
    return true;
}

export function DebugDetailsFromJSON(json: any): DebugDetails {
    return DebugDetailsFromJSONTyped(json, false);
}

export function DebugDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'start_time': json['start_time'],
        'end_time': json['end_time'],
        'duration': DurationFromJSON(json['duration']),
        'server_name': json['server_name'],
        'smtp': DebugDetailsSmtpFromJSON(json['smtp']),
    };
}

export function DebugDetailsToJSON(json: any): DebugDetails {
    return DebugDetailsToJSONTyped(json, false);
}

export function DebugDetailsToJSONTyped(value?: DebugDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_time': value['start_time'],
        'end_time': value['end_time'],
        'duration': DurationToJSON(value['duration']),
        'server_name': value['server_name'],
        'smtp': DebugDetailsSmtpToJSON(value['smtp']),
    };
}

