/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifMethod } from './VerifMethod';
import {
    VerifMethodFromJSON,
    VerifMethodFromJSONTyped,
    VerifMethodToJSON,
    VerifMethodToJSONTyped,
} from './VerifMethod';

/**
 * SMTP details used for debugging, including the verification method.
 * @export
 * @interface DebugDetailsSmtp
 */
export interface DebugDetailsSmtp {
    /**
     * 
     * @type {VerifMethod}
     * @memberof DebugDetailsSmtp
     */
    verif_method?: VerifMethod;
}

/**
 * Check if a given object implements the DebugDetailsSmtp interface.
 */
export function instanceOfDebugDetailsSmtp(value: object): value is DebugDetailsSmtp {
    return true;
}

export function DebugDetailsSmtpFromJSON(json: any): DebugDetailsSmtp {
    return DebugDetailsSmtpFromJSONTyped(json, false);
}

export function DebugDetailsSmtpFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugDetailsSmtp {
    if (json == null) {
        return json;
    }
    return {
        
        'verif_method': json['verif_method'] == null ? undefined : VerifMethodFromJSON(json['verif_method']),
    };
}

export function DebugDetailsSmtpToJSON(json: any): DebugDetailsSmtp {
    return DebugDetailsSmtpToJSONTyped(json, false);
}

export function DebugDetailsSmtpToJSONTyped(value?: DebugDetailsSmtp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verif_method': VerifMethodToJSON(value['verif_method']),
    };
}

