/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetV1Bulk200ResponseSummary } from './GetV1Bulk200ResponseSummary';
import {
    GetV1Bulk200ResponseSummaryFromJSON,
    GetV1Bulk200ResponseSummaryFromJSONTyped,
    GetV1Bulk200ResponseSummaryToJSON,
    GetV1Bulk200ResponseSummaryToJSONTyped,
} from './GetV1Bulk200ResponseSummary';

/**
 * 
 * @export
 * @interface GetV1Bulk200Response
 */
export interface GetV1Bulk200Response {
    /**
     * 
     * @type {number}
     * @memberof GetV1Bulk200Response
     */
    job_id: number;
    /**
     * The date and time when the bulk verification job was created.
     * @type {Date}
     * @memberof GetV1Bulk200Response
     */
    created_at: Date;
    /**
     * If the bulk verification job is completed, the date and time when it was finished.
     * @type {Date}
     * @memberof GetV1Bulk200Response
     */
    finished_at?: Date;
    /**
     * The number of emails to verify in the bulk verification job.
     * @type {number}
     * @memberof GetV1Bulk200Response
     */
    total_records: number;
    /**
     * The number of emails that have been verified at the time of the query.
     * @type {number}
     * @memberof GetV1Bulk200Response
     */
    total_processed: number;
    /**
     * 
     * @type {GetV1Bulk200ResponseSummary}
     * @memberof GetV1Bulk200Response
     */
    summary: GetV1Bulk200ResponseSummary;
    /**
     * The status of the job, either "Running" or "Completed".
     * @type {string}
     * @memberof GetV1Bulk200Response
     */
    job_status: GetV1Bulk200ResponseJobStatusEnum;
}


/**
 * @export
 */
export const GetV1Bulk200ResponseJobStatusEnum = {
    Running: 'Running',
    Completed: 'Completed'
} as const;
export type GetV1Bulk200ResponseJobStatusEnum = typeof GetV1Bulk200ResponseJobStatusEnum[keyof typeof GetV1Bulk200ResponseJobStatusEnum];


/**
 * Check if a given object implements the GetV1Bulk200Response interface.
 */
export function instanceOfGetV1Bulk200Response(value: object): value is GetV1Bulk200Response {
    if (!('job_id' in value) || value['job_id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('total_records' in value) || value['total_records'] === undefined) return false;
    if (!('total_processed' in value) || value['total_processed'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('job_status' in value) || value['job_status'] === undefined) return false;
    return true;
}

export function GetV1Bulk200ResponseFromJSON(json: any): GetV1Bulk200Response {
    return GetV1Bulk200ResponseFromJSONTyped(json, false);
}

export function GetV1Bulk200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1Bulk200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'job_id': json['job_id'],
        'created_at': (new Date(json['created_at'])),
        'finished_at': json['finished_at'] == null ? undefined : (new Date(json['finished_at'])),
        'total_records': json['total_records'],
        'total_processed': json['total_processed'],
        'summary': GetV1Bulk200ResponseSummaryFromJSON(json['summary']),
        'job_status': json['job_status'],
    };
}

export function GetV1Bulk200ResponseToJSON(json: any): GetV1Bulk200Response {
    return GetV1Bulk200ResponseToJSONTyped(json, false);
}

export function GetV1Bulk200ResponseToJSONTyped(value?: GetV1Bulk200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['job_id'],
        'created_at': ((value['created_at']).toISOString()),
        'finished_at': value['finished_at'] == null ? undefined : ((value['finished_at']).toISOString()),
        'total_records': value['total_records'],
        'total_processed': value['total_processed'],
        'summary': GetV1Bulk200ResponseSummaryToJSON(value['summary']),
        'job_status': value['job_status'],
    };
}

