/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckEmailOutput } from './CheckEmailOutput';
import {
    CheckEmailOutputFromJSON,
    CheckEmailOutputFromJSONTyped,
    CheckEmailOutputToJSON,
    CheckEmailOutputToJSONTyped,
} from './CheckEmailOutput';

/**
 * 
 * @export
 * @interface GetV1BulkResults200Response
 */
export interface GetV1BulkResults200Response {
    /**
     * 
     * @type {CheckEmailOutput}
     * @memberof GetV1BulkResults200Response
     */
    results: CheckEmailOutput;
}

/**
 * Check if a given object implements the GetV1BulkResults200Response interface.
 */
export function instanceOfGetV1BulkResults200Response(value: object): value is GetV1BulkResults200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function GetV1BulkResults200ResponseFromJSON(json: any): GetV1BulkResults200Response {
    return GetV1BulkResults200ResponseFromJSONTyped(json, false);
}

export function GetV1BulkResults200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1BulkResults200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': CheckEmailOutputFromJSON(json['results']),
    };
}

export function GetV1BulkResults200ResponseToJSON(json: any): GetV1BulkResults200Response {
    return GetV1BulkResults200ResponseToJSONTyped(json, false);
}

export function GetV1BulkResults200ResponseToJSONTyped(value?: GetV1BulkResults200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': CheckEmailOutputToJSON(value['results']),
    };
}

