/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration describing the method used to verify Gmail emails.
 * @export
 */
export const GmailVerifMethod = {
    Api: 'Api',
    Smtp: 'Smtp'
} as const;
export type GmailVerifMethod = typeof GmailVerifMethod[keyof typeof GmailVerifMethod];


export function instanceOfGmailVerifMethod(value: any): boolean {
    for (const key in GmailVerifMethod) {
        if (Object.prototype.hasOwnProperty.call(GmailVerifMethod, key)) {
            if (GmailVerifMethod[key as keyof typeof GmailVerifMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GmailVerifMethodFromJSON(json: any): GmailVerifMethod {
    return GmailVerifMethodFromJSONTyped(json, false);
}

export function GmailVerifMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): GmailVerifMethod {
    return json as GmailVerifMethod;
}

export function GmailVerifMethodToJSON(value?: GmailVerifMethod | null): any {
    return value as any;
}

export function GmailVerifMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): GmailVerifMethod {
    return value as GmailVerifMethod;
}

