/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration describing the method used to verify Hotmail B2C emails.
 * @export
 */
export const HotmailB2CVerifMethod = {
    Smtp: 'Smtp',
    Headless: 'Headless',
    Api: 'Api'
} as const;
export type HotmailB2CVerifMethod = typeof HotmailB2CVerifMethod[keyof typeof HotmailB2CVerifMethod];


export function instanceOfHotmailB2CVerifMethod(value: any): boolean {
    for (const key in HotmailB2CVerifMethod) {
        if (Object.prototype.hasOwnProperty.call(HotmailB2CVerifMethod, key)) {
            if (HotmailB2CVerifMethod[key as keyof typeof HotmailB2CVerifMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HotmailB2CVerifMethodFromJSON(json: any): HotmailB2CVerifMethod {
    return HotmailB2CVerifMethodFromJSONTyped(json, false);
}

export function HotmailB2CVerifMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): HotmailB2CVerifMethod {
    return json as HotmailB2CVerifMethod;
}

export function HotmailB2CVerifMethodToJSON(value?: HotmailB2CVerifMethod | null): any {
    return value as any;
}

export function HotmailB2CVerifMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): HotmailB2CVerifMethod {
    return value as HotmailB2CVerifMethod;
}

