/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration describing the method used to verify Hotmail B2B emails.
 * @export
 */
export const HotmailB2BVerifMethod = {
    Smtp: 'Smtp'
} as const;
export type HotmailB2BVerifMethod = typeof HotmailB2BVerifMethod[keyof typeof HotmailB2BVerifMethod];


export function instanceOfHotmailB2BVerifMethod(value: any): boolean {
    for (const key in HotmailB2BVerifMethod) {
        if (Object.prototype.hasOwnProperty.call(HotmailB2BVerifMethod, key)) {
            if (HotmailB2BVerifMethod[key as keyof typeof HotmailB2BVerifMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HotmailB2BVerifMethodFromJSON(json: any): HotmailB2BVerifMethod {
    return HotmailB2BVerifMethodFromJSONTyped(json, false);
}

export function HotmailB2BVerifMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): HotmailB2BVerifMethod {
    return json as HotmailB2BVerifMethod;
}

export function HotmailB2BVerifMethodToJSON(value?: HotmailB2BVerifMethod | null): any {
    return value as any;
}

export function HotmailB2BVerifMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): HotmailB2BVerifMethod {
    return value as HotmailB2BVerifMethod;
}

