/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Additional information about the email account.
 * @export
 * @interface MiscDetails
 */
export interface MiscDetails {
    /**
     * Indicates if the email address is from a known disposable email provider.
     * @type {boolean}
     * @memberof MiscDetails
     */
    is_disposable: boolean;
    /**
     * Indicates if the email address is a role-based account.
     * @type {boolean}
     * @memberof MiscDetails
     */
    is_role_account: boolean;
    /**
     * URL to the Gravatar profile picture associated with the email, if available and requested.
     * @type {string}
     * @memberof MiscDetails
     */
    gravatar_url?: string;
    /**
     * Is this a B2C email address?
     * @type {boolean}
     * @memberof MiscDetails
     */
    is_b2c: boolean;
}

/**
 * Check if a given object implements the MiscDetails interface.
 */
export function instanceOfMiscDetails(value: object): value is MiscDetails {
    if (!('is_disposable' in value) || value['is_disposable'] === undefined) return false;
    if (!('is_role_account' in value) || value['is_role_account'] === undefined) return false;
    if (!('is_b2c' in value) || value['is_b2c'] === undefined) return false;
    return true;
}

export function MiscDetailsFromJSON(json: any): MiscDetails {
    return MiscDetailsFromJSONTyped(json, false);
}

export function MiscDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MiscDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'is_disposable': json['is_disposable'],
        'is_role_account': json['is_role_account'],
        'gravatar_url': json['gravatar_url'] == null ? undefined : json['gravatar_url'],
        'is_b2c': json['is_b2c'],
    };
}

export function MiscDetailsToJSON(json: any): MiscDetails {
    return MiscDetailsToJSONTyped(json, false);
}

export function MiscDetailsToJSONTyped(value?: MiscDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_disposable': value['is_disposable'],
        'is_role_account': value['is_role_account'],
        'gravatar_url': value['gravatar_url'],
        'is_b2c': value['is_b2c'],
    };
}

