/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details about the mail server's MX records.
 * @export
 * @interface MxDetails
 */
export interface MxDetails {
    /**
     * Indicates if the mail server accepts emails.
     * @type {boolean}
     * @memberof MxDetails
     */
    accepts_mail: boolean;
    /**
     * List of Fully Qualified Domain Names (FQDN) of the mail server.
     * @type {Array<string>}
     * @memberof MxDetails
     */
    records: Array<string>;
}

/**
 * Check if a given object implements the MxDetails interface.
 */
export function instanceOfMxDetails(value: object): value is MxDetails {
    if (!('accepts_mail' in value) || value['accepts_mail'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function MxDetailsFromJSON(json: any): MxDetails {
    return MxDetailsFromJSONTyped(json, false);
}

export function MxDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MxDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'accepts_mail': json['accepts_mail'],
        'records': json['records'],
    };
}

export function MxDetailsToJSON(json: any): MxDetails {
    return MxDetailsToJSONTyped(json, false);
}

export function MxDetailsToJSONTyped(value?: MxDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepts_mail': value['accepts_mail'],
        'records': value['records'],
    };
}

