/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskWebhook } from './TaskWebhook';
import {
    TaskWebhookFromJSON,
    TaskWebhookFromJSONTyped,
    TaskWebhookToJSON,
    TaskWebhookToJSONTyped,
} from './TaskWebhook';

/**
 * 
 * @export
 * @interface PostV1BulkRequest
 */
export interface PostV1BulkRequest {
    /**
     * A list of emails to verify.
     * @type {Array<string>}
     * @memberof PostV1BulkRequest
     */
    input: Array<string>;
    /**
     * 
     * @type {TaskWebhook}
     * @memberof PostV1BulkRequest
     */
    webhook?: TaskWebhook;
}

/**
 * Check if a given object implements the PostV1BulkRequest interface.
 */
export function instanceOfPostV1BulkRequest(value: object): value is PostV1BulkRequest {
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function PostV1BulkRequestFromJSON(json: any): PostV1BulkRequest {
    return PostV1BulkRequestFromJSONTyped(json, false);
}

export function PostV1BulkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV1BulkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'],
        'webhook': json['webhook'] == null ? undefined : TaskWebhookFromJSON(json['webhook']),
    };
}

export function PostV1BulkRequestToJSON(json: any): PostV1BulkRequest {
    return PostV1BulkRequestToJSONTyped(json, false);
}

export function PostV1BulkRequestToJSONTyped(value?: PostV1BulkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'webhook': TaskWebhookToJSON(value['webhook']),
    };
}

