/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration describing the confidence level that the recipient address is valid: `safe`, `risky`, `invalid`, or `unknown`. Refer to our FAQ for detailed definitions: https://help.reacher.email/email-attributes-inside-json.
 * @export
 */
export const Reachable = {
    Invalid: 'invalid',
    Unknown: 'unknown',
    Safe: 'safe',
    Risky: 'risky'
} as const;
export type Reachable = typeof Reachable[keyof typeof Reachable];


export function instanceOfReachable(value: any): boolean {
    for (const key in Reachable) {
        if (Object.prototype.hasOwnProperty.call(Reachable, key)) {
            if (Reachable[key as keyof typeof Reachable] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReachableFromJSON(json: any): Reachable {
    return ReachableFromJSONTyped(json, false);
}

export function ReachableFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reachable {
    return json as Reachable;
}

export function ReachableToJSON(value?: Reachable | null): any {
    return value as any;
}

export function ReachableToJSONTyped(value: any, ignoreDiscriminator: boolean): Reachable {
    return value as Reachable;
}

