/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Results from SMTP connection attempts to the mail server.
 * @export
 * @interface SmtpDetails
 */
export interface SmtpDetails {
    /**
     * Indicates if the mail exchanger can be contacted successfully.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    can_connect_smtp: boolean;
    /**
     * Indicates if the mailbox is full.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    has_full_inbox: boolean;
    /**
     * Indicates if the email address is a catch-all address.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    is_catch_all: boolean;
    /**
     * Indicates if an email sent to this address is deliverable.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    is_deliverable: boolean;
    /**
     * Indicates if the email address has been disabled by the provider.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    is_disabled: boolean;
}

/**
 * Check if a given object implements the SmtpDetails interface.
 */
export function instanceOfSmtpDetails(value: object): value is SmtpDetails {
    if (!('can_connect_smtp' in value) || value['can_connect_smtp'] === undefined) return false;
    if (!('has_full_inbox' in value) || value['has_full_inbox'] === undefined) return false;
    if (!('is_catch_all' in value) || value['is_catch_all'] === undefined) return false;
    if (!('is_deliverable' in value) || value['is_deliverable'] === undefined) return false;
    if (!('is_disabled' in value) || value['is_disabled'] === undefined) return false;
    return true;
}

export function SmtpDetailsFromJSON(json: any): SmtpDetails {
    return SmtpDetailsFromJSONTyped(json, false);
}

export function SmtpDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmtpDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'can_connect_smtp': json['can_connect_smtp'],
        'has_full_inbox': json['has_full_inbox'],
        'is_catch_all': json['is_catch_all'],
        'is_deliverable': json['is_deliverable'],
        'is_disabled': json['is_disabled'],
    };
}

export function SmtpDetailsToJSON(json: any): SmtpDetails {
    return SmtpDetailsToJSONTyped(json, false);
}

export function SmtpDetailsToJSONTyped(value?: SmtpDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_connect_smtp': value['can_connect_smtp'],
        'has_full_inbox': value['has_full_inbox'],
        'is_catch_all': value['is_catch_all'],
        'is_deliverable': value['is_deliverable'],
        'is_disabled': value['is_disabled'],
    };
}

