/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration describing the method used to verify Yahoo emails.
 * @export
 */
export const YahooVerifMethod = {
    Api: 'Api',
    Headless: 'Headless',
    Smtp: 'Smtp'
} as const;
export type YahooVerifMethod = typeof YahooVerifMethod[keyof typeof YahooVerifMethod];


export function instanceOfYahooVerifMethod(value: any): boolean {
    for (const key in YahooVerifMethod) {
        if (Object.prototype.hasOwnProperty.call(YahooVerifMethod, key)) {
            if (YahooVerifMethod[key as keyof typeof YahooVerifMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function YahooVerifMethodFromJSON(json: any): YahooVerifMethod {
    return YahooVerifMethodFromJSONTyped(json, false);
}

export function YahooVerifMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): YahooVerifMethod {
    return json as YahooVerifMethod;
}

export function YahooVerifMethodToJSON(value?: YahooVerifMethod | null): any {
    return value as any;
}

export function YahooVerifMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): YahooVerifMethod {
    return value as YahooVerifMethod;
}

